# .prettierrc.yml
# see: https://prettier.io/docs/en/options.html
printWidth: 80
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: always
proseWrap: always
